{
  shop = {
    { text = "Нано-ботинки", price = "7", label = "NanoSuit Boots" },
    { text = "Нано-кираса", price = "8", label = "NanoSuit Bodyarmor" },
    { text = "Нано-поножи", price = "7", label = "NanoSuit Leggings" },
    { text = "Нано-сабля", price = "7", label = "Nano Saber" },
    { text = "Нано-шлем", price = "8", label = "NanoSuit Helmet" },
    { text = "Солнечная панель ур 1", price = "2", label = "Solar Panel" },
    { text = "Солнечная панель ур 2", price = "17", label = "Low Voltage Solar Array" },
    { text = "Солнечная панель ур 3", price = "139", label = "Medium Voltage Solar Array" },
    { text = "Солнечная панель ур 4", price = "1160", label = "High Voltage Solar Array" },
    { text = "Улучшение (ускоритель)", price = "18", label = "Overclocker Upgrade" },
    { text = "Улучшенный алмазный бур", price = "52", label = "Advanced Diamond Drill" },
    { text = "Улучшенный наножилет", price = "75", label = "Advanced NanoChestPlate" },
    { text = "Уникальный чертёж", price = "11", label = "item.Epic_plan.name" },
    { text = "Флаксовый конденсатор Виверны", price = "899", label = "Wyvern Flux Capacitor" },
    { text = "Шахтёрский лазер", price = "8", label = "Mining Laser" },
    { text = "Шлем Виверны", price = "480", label = "Wyvern Helm" },
    { text = "ЭХПФ", price = "427", label = "AFSU" },
    { text = "Элемент огня", price = "173", label = "Fire Element" },
    { text = "Элемент тьмы", price = "300", label = "item.Dark_element.name" },
    { text = "Энергетическое ядро виверны", price = "29", label = "Wyvern Energy Core" },
    { text = "Ядро виверны", price = "220", label = "Wyvern Core" },
    { text = "Улучшенная переносная ячейка", price = "25", label = "item.advancedPortableCell.name" },
    { text = "Гибридная переносная ячейка", price = "94", label = "item.hybridPortableCell.name" },
    { text = "Совершенная переносная ячейка", price = "351", label = "item.ultimatePortableCell.name" },
{ text = "Совершенная переносная ячейка", price = "351", label = "item.ultimatePortableCell.name" },
}
}
